FROM gliderlabs/alpine:3.1
CMD ["/bin/r53-registrator"]

ENV GOPATH /go
RUN apk-install go git mercurial
COPY . /go/src/github.com/Rob-Johnson/route53-registrator
WORKDIR /go/src/github.com/Rob-Johnson/route53-registrator
RUN go get
RUN go build -ldflags "-X main.Version dev" -o /bin/r53-registrator

